### ISSUE TITLE
[1.16.1] Weird Error

### ISSUE THREAD

**Issue by ClockworkFountain** [SmellyModder/Seeker-Compass#6]
Occurs in early loading stages of boot-up
[Latest.log](https://pastebin.com/zJVX0QUc)
[Crash Report](https://pastebin.com/vizL5s3E)

**Comment by SmellyModder** [comment]
This doesn't look like an issue caused by this mod.
Have you tried removing Seeker Compass and seeing if the crash still happens?

**Comment by ClockworkFountain** [comment]
I’d have to check, it’s been a while since I’ve tried to boot up that pack due to the newer versions of forge.

**Comment by electric-ajax** [comment]
I have this exact issue. When it finishes loading it says that there's "missing files" for the mod. I tried without it and it worked fine.

**Comment by SmellyModder** [comment]
Fixed in commit https://github.com/SmellyModder/Seeker-Compass/commit/03dc913bdc254942bdcb19c84ffc4bad8771a96d
The new version on Curseforge includes this fix.
